//! YAML policy writer

use std::fs::File;
use std::io::Write;
use std::path::Path;

use anyhow::{Context, Result};

use scmm_common::policy::YamlPolicy;

/// Write policy to YAML file
pub fn write_policy(path: &Path, policy: &YamlPolicy) -> Result<()> {
    let yaml = serde_yaml::to_string(policy).context("Failed to serialize policy")?;

    // Add header comment
    let header = r#"# SysCallMeMaybe (SCMM) Policy File
# Generated by scmm-extract
#
# Use 'scmm-compile' to compile this policy for enforcement:
#   scmm-compile -i policy.scmm.yaml -o policy.scmm-pol
#
# Then use 'scmm-enforce' to run a program with this policy:
#   scmm-enforce -p policy.scmm-pol -- ./my-program
#
"#;

    let mut file = File::create(path).context("Failed to create policy file")?;
    file.write_all(header.as_bytes())?;
    file.write_all(yaml.as_bytes())?;

    Ok(())
}
